name: emg_cnn
channels:
  - defaults
dependencies:
  - python>=3.6
  - pip
  - numpy==1.18.5
  - scipy==1.4.1
  - matplotlib==3.2.2
  - pip:
      - environs==8.0.0
      - PyYAML==5.3.1
      - PyWavelets==1.1.1
