class ActionKind:
    BOWING = "Bowing"
    CLAPPING = "Clapping"
    HANDSHAKING = "Handshaking"
    HUGGING = "Hugging"
    JUMPING = "Jumping"
    RUNNING = "Running"
    SEATING = "Seating"
    STANDING = "Standing"
    WALKING = "Walking"
    WAVING = "Waving"
    ELBOWING = "Elbowing"
    FRONTKICKING = "Frontkicking"
    HAMERING = "Hamering"
    HEADERING = "Headering"
    KNEEING = "Kneeing"
    PULLING = "Pulling"
    PUNCHING = "Punching"
    PUSHING = "Pushing"
    SIDEKICKING = "Sidekicking"
    SLAPPING = "Slapping"

